from __future__ import annotations

from pathlib import Path

import pytest

from slanq.cli import main

EXAMPLES = Path(__file__).parent.parent / "examples"
MVP_A = str(EXAMPLES / "mvp_a.slanq")


def test_parse_prints_the_tree(capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["parse", MVP_A]) == 0
    assert "qbool_decl" in capsys.readouterr().out


def test_compile_writes_to_stdout(capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["compile", MVP_A]) == 0
    out = capsys.readouterr().out
    assert out.startswith("# Generated by Slanq ")
    assert "circuit.h(q[0])" in out


def test_compile_writes_to_file(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    destination = tmp_path / "out.py"
    assert main(["compile", MVP_A, "-o", str(destination)]) == 0
    assert capsys.readouterr().out == ""
    assert "def build_circuit()" in destination.read_text(encoding="utf-8")


def test_missing_file_reports_usage_error(capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["compile", str(EXAMPLES / "does_not_exist.slanq")]) == 2
    assert "Could not read file" in capsys.readouterr().err


def test_semantic_error_reports_compile_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    source = tmp_path / "bad.slanq"
    source.write_text("H(unknown);\n", encoding="utf-8")

    assert main(["compile", str(source)]) == 1
    assert "undefined name" in capsys.readouterr().err


def test_syntax_error_reports_compile_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    source = tmp_path / "bad.slanq"
    source.write_text("qbool q = ;\n", encoding="utf-8")

    assert main(["compile", str(source)]) == 1
    assert "Syntax error" in capsys.readouterr().err


def test_missing_command_exits_with_usage_error() -> None:
    with pytest.raises(SystemExit) as excinfo:
        main([])
    assert excinfo.value.code == 2
