from __future__ import annotations

import math
import sys
from typing import Any

import numpy
import pytest

from slanq.analysis import analyze
from slanq.ast_nodes import Literal, Span
from slanq.builtin import _round_half_away, _sqrt, const_value
from slanq.codegen import _Generator, generate_qiskit
from slanq.compiler import compile_source
from slanq.diagnostics import DiagnosticBag, SlanqError
from slanq.ir import (
    ArithmeticOp,
    ClbitRef,
    DeclareAncillaOp,
    GateOp,
    InitOp,
    IRBlock,
    IRModule,
    MultiplyOp,
    ParamInfo,
    PhaseOp,
    QIfClauseAncilla,
    QIfOp,
    QubitBit,
    QubitRef,
    QubitSlice,
)


def _generate(module: IRModule) -> str:
    return generate_qiskit(module, source_name="mvp_a.slanq")


def test_output_is_valid_python(mvp_a_ir: IRModule) -> None:
    compile(_generate(mvp_a_ir), "<generated>", "exec")


def test_header_names_the_source(mvp_a_ir: IRModule) -> None:
    first_line = _generate(mvp_a_ir).splitlines()[0]
    assert first_line.startswith("# Generated by Slanq ")
    assert first_line.endswith(" from mvp_a.slanq")


def test_registers_and_circuit_are_declared(mvp_a_ir: IRModule) -> None:
    source = _generate(mvp_a_ir)
    assert 'q = QuantumRegister(1, "q")' in source
    assert 'result = ClassicalRegister(1, "result")' in source
    assert "circuit = QuantumCircuit(q, result)" in source


def test_gate_and_measurement_are_emitted(mvp_a_ir: IRModule) -> None:
    source = _generate(mvp_a_ir)
    assert "circuit.h(q[0])" in source
    assert "circuit.measure(q, result)" in source


def test_function_and_main_guard(mvp_a_ir: IRModule) -> None:
    source = _generate(mvp_a_ir)
    assert "def build_circuit() -> QuantumCircuit:" in source
    assert "return circuit" in source
    assert 'if __name__ == "__main__":' in source


def test_main_guard_forces_utf8_stdout(mvp_a_ir: IRModule) -> None:
    source = _generate(mvp_a_ir)
    assert "import sys" in source
    assert 'sys.stdout.reconfigure(encoding="utf-8")' in source


class _StdoutWithoutReconfigure:
    """Stands in for a replaced sys.stdout (Jupyter %run, IDLE), which lacks
    TextIOWrapper.reconfigure -- has `encoding`, like a real IO-like
    replacement, so only the missing `reconfigure` is under test."""

    encoding = "utf-8"

    def write(self, text: str) -> int:
        return len(text)

    def flush(self) -> None:
        pass


def test_utf8_stdout_fix_is_guarded(mvp_a_ir: IRModule) -> None:
    """An unguarded `reconfigure()` call would raise AttributeError when
    something replaced sys.stdout -- worse than the UnicodeEncodeError it
    exists to prevent. Runs the generated __main__ block for real, not just
    checking the guard text is present."""
    source = _generate(mvp_a_ir)
    assert 'if hasattr(sys.stdout, "reconfigure"):' in source

    original_stdout = sys.stdout
    sys.stdout = _StdoutWithoutReconfigure()  # type: ignore[assignment]
    try:
        exec(compile(source, "<generated>", "exec"), {"__name__": "__main__"})  # noqa: S102
    finally:
        sys.stdout = original_stdout


def test_false_initializer_emits_nothing(mvp_a_ir: IRModule) -> None:
    assert "circuit.x(" not in _generate(mvp_a_ir)


def test_true_initializer_emits_an_x_gate(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(ops=[InitOp(span=span, target=qubit, value=True)]),
    )
    assert "circuit.x(q[0])" in _generate(module)


def test_import_omits_classical_register_when_unused(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    module = IRModule(qubits=[qubit], body=IRBlock(ops=[]))
    source = _generate(module)
    assert "from qiskit import QuantumCircuit, QuantumRegister" in source
    assert "ClassicalRegister" not in source


def test_params_precede_targets(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[
                GateOp(
                    span=span,
                    name="RX",
                    targets=[QubitBit(ref=qubit, index=0)],
                    params=[Literal(span=span, value=1.5)],
                )
            ]
        ),
    )
    assert "circuit.rx(1.5, q[0])" in _generate(module)


def test_whole_register_target_is_not_indexed(span: Span) -> None:
    qubit = QubitRef(name="a", size=3)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(ops=[GateOp(span=span, name="H", targets=[qubit])]),
    )
    assert "circuit.h(a)" in _generate(module)


def test_multi_qubit_constant_sets_the_right_bits(span: Span) -> None:
    """5 is 0b101; the register is little-endian, so bits 0 and 2 are flipped."""
    qubit = QubitRef(name="a", size=3)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(ops=[InitOp(span=span, target=qubit, value=5)]),
    )
    source = _generate(module)
    assert "circuit.x(a[0])" in source
    assert "circuit.x(a[2])" in source
    assert "circuit.x(a[1])" not in source


def test_index_is_mirrored_for_qiskit(span: Span) -> None:
    """Slanq's q[0] is the most significant qubit, Qiskit's q[0] the least."""
    qubit = QubitRef(name="q", size=3)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[GateOp(span=span, name="H", targets=[QubitBit(ref=qubit, index=0)])]
        ),
    )
    assert "circuit.h(q[2])" in _generate(module)


def test_single_qubit_register_needs_no_mirroring(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[GateOp(span=span, name="H", targets=[QubitBit(ref=qubit, index=0)])]
        ),
    )
    assert "circuit.h(q[0])" in _generate(module)


def test_generated_module_builds_a_runnable_circuit(mvp_a_ir: IRModule) -> None:
    namespace: dict[str, object] = {}
    exec(_generate(mvp_a_ir), namespace)  # noqa: S102
    circuit = namespace["build_circuit"]()
    assert circuit.num_qubits == 1
    assert circuit.num_clbits == 1


def test_unused_clbit_register_still_declared(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    clbit = ClbitRef(name="result", size=1)
    module = IRModule(qubits=[qubit], clbits=[clbit], body=IRBlock(ops=[]))
    assert 'result = ClassicalRegister(1, "result")' in _generate(module)


def _param_source(source: str) -> str:
    """The Python rendering of a single gate parameter written in Slanq."""
    result = compile_source(f"qbool q = false;\nRX({source}, q);\n")
    assert not result.diagnostics.has_errors
    assert result.qiskit_source is not None
    return result.qiskit_source


def test_pi_is_emitted_symbolically() -> None:
    source = _param_source("PI / 4")
    assert "circuit.rx(np.pi / 4, q[0])" in source
    assert "0.785" not in source


def test_numpy_is_imported_only_when_needed() -> None:
    assert "import numpy as np" in _param_source("PI")
    assert "import numpy as np" not in _param_source("1.5")


def test_round_helper_is_emitted_with_slanq_semantics() -> None:
    source = _param_source("round(2.5)")
    assert "circuit.rx(_round(2.5), q[0])" in source
    assert "def _round(value: float) -> int:" in source
    assert "import math" in source


def test_floor_and_ceil_map_to_math() -> None:
    source = _param_source("floor(7 / 2) * ceil(1.2)")
    assert "circuit.rx(math.floor(7 / 2) * math.ceil(1.2), q[0])" in source


def test_sqrt_maps_to_the_helper_as_an_angle_expression() -> None:
    source = _param_source("sqrt(2)")
    assert "circuit.rx(_sqrt(2), q[0])" in source
    assert "import math" in source


def test_classical_name_angle_inlines_its_initializer() -> None:
    result = compile_source("float t = PI / 4;\nqbool q = false;\nRX(t, q);\n")
    assert not result.diagnostics.has_errors
    assert result.qiskit_source is not None
    assert "circuit.rx(np.pi / 4, q[0])" in result.qiskit_source


@pytest.mark.parametrize(
    "slanq_source",
    [
        "PI / 4", "-PI", "2 ** 3 ** 2", "-2 ** 2", "(-2) ** 2", "2 ** -1",
        "1 - (2 - 3)", "(1 + 2) * 3", "1 + 2 * 3", "-7 % 3", "1 | 2 ^ 3 & 4",
        "(1 | 2) ^ 3", "~5 + 1", "-(1 + 2)", "100 / (2 * 5)", "1 / 2 / 4",
        "floor(PI * 2) + round(1.5)", "(1 - 2) ** 3",
    ],
)
def test_rendered_python_has_the_same_value_as_the_slanq_expression(
    build_ast, slanq_source: str
) -> None:
    """The parenthesising is what makes this hold: Slanq and Python agree on
    precedence only because the grammar was aligned with Python's table."""
    (declaration,) = build_ast(f"float r = {slanq_source};").statements
    rendered = _Generator().expression(declaration.initializer)
    namespace = {"np": numpy, "math": math, "_round": _round_half_away}
    assert eval(rendered, namespace) == const_value(declaration.initializer)  # noqa: S307


def test_unknown_gate_name_fails_loudly(span: Span) -> None:
    """Lower-casing the Slanq name would emit a method Qiskit does not have."""
    qubit = QubitRef(name="q", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(ops=[GateOp(span=span, name="phase", targets=[qubit])]),
    )
    with pytest.raises(SlanqError):
        _generate(module)


def test_empty_probability_list_becomes_hadamards(span: Span) -> None:
    qubit = QubitRef(name="a", size=2)
    module = IRModule(qubits=[qubit], body=IRBlock(ops=[InitOp(span=span, target=qubit, value=[])]))
    source = _generate(module)
    assert "circuit.h(a[0])" in source
    assert "circuit.h(a[1])" in source
    assert "StatePreparation" not in source


def test_nonempty_probability_list_becomes_state_preparation(span: Span) -> None:
    qubit = QubitRef(name="a", size=2)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(ops=[InitOp(span=span, target=qubit, value=[0.0, 0.0, 0.8, 0.2])]),
    )
    source = _generate(module)
    assert "from qiskit.circuit.library import StatePreparation" in source
    assert (
        "circuit.append(StatePreparation([0.0, 0.0, 0.8944271909999159, "
        "0.4472135954999579]), a)" in source
    )


def test_state_preparation_amplitudes_are_normalized_defensively(span: Span) -> None:
    """Even a list that is not exactly 1 (rejected upstream by analysis in
    practice) would not crash the codegen: it always divides by the sum."""
    qubit = QubitRef(name="a", size=1)
    module = IRModule(
        qubits=[qubit], body=IRBlock(ops=[InitOp(span=span, target=qubit, value=[1.0, 1.0])])
    )
    source = _generate(module)
    assert "StatePreparation([0.7071067811865476, 0.7071067811865476])" in source


def test_amplitude_list_becomes_normalized_state_preparation(span: Span) -> None:
    """Unlike a probability list, an amplitude list is not square-rooted --
    its raw values are already amplitudes, only divided by their L2 norm. No
    value_expressions here, so this exercises the numeric fallback path (the
    symbolic path is covered by test_normalized_amplitude_list_renders_symbolically
    below)."""
    qubit = QubitRef(name="a", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[
                InitOp(
                    span=span, target=qubit, value=[1.0, 1j], is_amplitude=True
                )
            ]
        ),
    )
    source = _generate(module)
    assert "from qiskit.circuit.library import StatePreparation" in source
    assert (
        "circuit.append(StatePreparation([0.7071067811865475, "
        "0.7071067811865475j]), a)" in source
    )


def test_normalized_amplitude_list_renders_symbolically(span: Span) -> None:
    """An already-normalized amplitude list with value_expressions set renders
    the original expressions (never-fold-a-compile-time-expression), not a
    decimal approximation."""
    qubit = QubitRef(name="a", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[
                InitOp(
                    span=span,
                    target=qubit,
                    value=[0.6, 0.8],
                    is_amplitude=True,
                    value_expressions=[
                        Literal(span=span, value=0.6),
                        Literal(span=span, value=0.8),
                    ],
                )
            ]
        ),
    )
    source = _generate(module)
    assert "circuit.append(StatePreparation([0.6, 0.8]), a)" in source


def test_off_normalized_amplitude_list_ignores_value_expressions(span: Span) -> None:
    """A genuine correction is needed, so the symbolic path must not be taken
    even when value_expressions is present -- the expressions would no longer
    describe the actual (normalized) amplitudes."""
    qubit = QubitRef(name="a", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[
                InitOp(
                    span=span,
                    target=qubit,
                    value=[0.6, 0.6],
                    is_amplitude=True,
                    value_expressions=[
                        Literal(span=span, value=0.6),
                        Literal(span=span, value=0.6),
                    ],
                )
            ]
        ),
    )
    source = _generate(module)
    assert "StatePreparation([0.6, 0.6])" not in source
    assert "0.7071067811865475" in source


def test_amplitude_list_preserves_complex_values(span: Span) -> None:
    qubit = QubitRef(name="a", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[InitOp(span=span, target=qubit, value=[1j, 0.0], is_amplitude=True)]
        ),
    )
    source = _generate(module)
    assert "1j" in source


def test_empty_amplitude_list_becomes_hadamards(span: Span) -> None:
    qubit = QubitRef(name="a", size=2)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(ops=[InitOp(span=span, target=qubit, value=[], is_amplitude=True)]),
    )
    source = _generate(module)
    assert "circuit.h(a[0])" in source
    assert "circuit.h(a[1])" in source
    assert "StatePreparation" not in source


def test_qif_direct_control_when_not_negated(span: Span) -> None:
    condition = QubitRef(name="a", size=2)
    body_target = QubitRef(name="out", size=1)
    module = IRModule(
        qubits=[condition, body_target],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[condition],
                    ctrl_state=2,
                    clause_ancillas=[],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(
                        ops=[GateOp(span=span, name="X", targets=[body_target])]
                    ),
                )
            ]
        ),
    )
    source = _generate(module)
    # One wire per qubit the body touches, never a whole register -- see
    # test_qif_control_and_target_in_one_register_do_not_collide.
    assert '_qif_body_1 = QuantumCircuit(1, name="qif_body")' in source
    assert "_qif_body_1.x(_qif_body_1.qubits[0])" in source
    assert (
        "circuit.append(_qif_body_1.to_gate().control(2, ctrl_state=2, "
        "annotated=False), [*a, out[0]])" in source
    )
    assert "add_register" not in source
    assert "XGate" not in source


def test_qif_negated_uses_an_ancilla(span: Span) -> None:
    condition = QubitRef(name="a", size=2)
    body_target = QubitRef(name="out", size=1)
    ancilla = QubitRef(name="_ancilla_0", size=1)
    module = IRModule(
        qubits=[condition, body_target],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[condition],
                    ctrl_state=2,
                    clause_ancillas=[],
                    negated=True,
                    ancilla=ancilla,
                    body=IRBlock(
                        ops=[GateOp(span=span, name="X", targets=[body_target])]
                    ),
                )
            ]
        ),
    )
    source = _generate(module)
    assert "from qiskit.circuit.library import XGate" in source
    assert (
        "circuit.append(XGate().control(2, ctrl_state=2, annotated=False), "
        "[*a, _ancilla_0[0]])" in source
    )
    assert "circuit.x(_ancilla_0[0])" in source
    assert (
        "circuit.append(_qif_body_1.to_gate().control(1, ctrl_state=1, "
        "annotated=False), [_ancilla_0[0], out[0]])" in source
    )


def _phase_only_qif(span: Span, ctrl_state: int) -> IRModule:
    condition = QubitRef(name="a", size=2)
    return IRModule(
        qubits=[condition],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[condition],
                    ctrl_state=ctrl_state,
                    clause_ancillas=[],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(
                        ops=[PhaseOp(span=span, angle=Literal(span=span, value=1.5))]
                    ),
                )
            ]
        ),
    )


def test_qif_phase_only_body_becomes_a_phase_gate_on_the_condition(span: Span) -> None:
    """A controlled global phase is a phase gate on the control qubits, so no
    sub-circuit is built at all -- a 0-wire one cannot be drawn once
    controlled, and drawing is what the generated file's __main__ does."""
    source = _generate(_phase_only_qif(span, ctrl_state=2))
    assert "QuantumCircuit(0" not in source
    assert "qif_body" not in source
    assert "circuit.mcp(1.5, [a[0]], a[1])" in source


def test_qif_phase_only_body_conjugates_the_zero_controls(span: Span) -> None:
    """A phase gate fires on |1...1>, so every control the condition wants at
    zero -- here a[0], since ctrl_state 2 is 0b10 -- is X-conjugated."""
    source = _generate(_phase_only_qif(span, ctrl_state=2))
    lines = [line.strip() for line in source.splitlines()]
    phase = lines.index("circuit.mcp(1.5, [a[0]], a[1])")
    assert lines[phase - 1] == "circuit.x(a[0])"
    assert lines[phase + 1] == "circuit.x(a[0])"


def test_qif_phase_only_body_needs_no_conjugation_on_an_all_ones_condition(
    span: Span,
) -> None:
    source = _generate(_phase_only_qif(span, ctrl_state=3))
    assert "circuit.x(" not in source
    assert "circuit.mcp(1.5, [a[0]], a[1])" in source


def test_qif_single_qubit_condition_takes_a_plain_phase_gate(span: Span) -> None:
    condition = QubitRef(name="a", size=1)
    module = IRModule(
        qubits=[condition],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[condition],
                    ctrl_state=1,
                    clause_ancillas=[],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(
                        ops=[PhaseOp(span=span, angle=Literal(span=span, value=1.5))]
                    ),
                )
            ]
        ),
    )
    source = _generate(module)
    assert "circuit.p(1.5, a[0])" in source


def test_qif_phases_are_summed_into_one_gate(span: Span) -> None:
    condition = QubitRef(name="a", size=1)
    module = IRModule(
        qubits=[condition],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[condition],
                    ctrl_state=1,
                    clause_ancillas=[],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(
                        ops=[
                            PhaseOp(span=span, angle=Literal(span=span, value=1.5)),
                            PhaseOp(span=span, angle=Literal(span=span, value=0.25)),
                        ]
                    ),
                )
            ]
        ),
    )
    source = _generate(module)
    assert "circuit.p(1.5 + 0.25, a[0])" in source


def test_qif_mixed_body_keeps_the_gates_in_a_sub_circuit(span: Span) -> None:
    """The phase leaves the sub-circuit even when the body has gates too, so
    there is one rule for a body phase and not two."""
    condition = QubitRef(name="a", size=2)
    body_target = QubitRef(name="out", size=1)
    module = IRModule(
        qubits=[condition, body_target],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[condition],
                    ctrl_state=2,
                    clause_ancillas=[],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(
                        ops=[
                            PhaseOp(span=span, angle=Literal(span=span, value=1.5)),
                            GateOp(span=span, name="X", targets=[body_target]),
                        ]
                    ),
                )
            ]
        ),
    )
    source = _generate(module)
    assert "global_phase" not in source
    assert '_qif_body_1 = QuantumCircuit(1, name="qif_body")' in source
    assert (
        "circuit.append(_qif_body_1.to_gate().control(2, ctrl_state=2, "
        "annotated=False), [*a, out[0]])" in source
    )
    assert "circuit.mcp(1.5, [a[0]], a[1])" in source


def test_qif_empty_body_generates_nothing(span: Span) -> None:
    condition = QubitRef(name="a", size=2)
    module = IRModule(
        qubits=[condition],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[condition],
                    ctrl_state=2,
                    clause_ancillas=[],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(ops=[]),
                )
            ]
        ),
    )
    source = _generate(module)
    assert "qif_body" not in source
    assert "circuit.x(" not in source
    assert "circuit.p(" not in source


def test_qif_indexed_condition_qubit_mirrors(span: Span) -> None:
    """A QubitBit condition entry is an explicit index and must mirror, unlike
    a QubitRef entry which is a whole-register value test and must not."""
    condition = QubitRef(name="a", size=3)
    body_target = QubitRef(name="out", size=1)
    module = IRModule(
        qubits=[condition, body_target],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[QubitBit(ref=condition, index=0)],
                    ctrl_state=1,
                    clause_ancillas=[],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(
                        ops=[GateOp(span=span, name="X", targets=[body_target])]
                    ),
                )
            ]
        ),
    )
    source = _generate(module)
    # Slanq index 0 on a size-3 register mirrors to Qiskit position 2.
    assert "[a[2], out[0]]" in source


def test_qif_control_and_target_in_one_register_do_not_collide(span: Span) -> None:
    """`qif(a[0]) { X(a[1]); }` -- different qubits, so the program is legal
    and analysis allows it, but a whole-register body sub-circuit used to
    unpack a[0] into the append list a second time, next to the control, and
    the generated file died with `CircuitError: duplicate bit arguments`."""
    register = QubitRef(name="a", size=2)
    module = IRModule(
        qubits=[register],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[QubitBit(ref=register, index=0)],
                    ctrl_state=1,
                    clause_ancillas=[],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(
                        ops=[
                            GateOp(
                                span=span,
                                name="X",
                                targets=[QubitBit(ref=register, index=1)],
                            )
                        ]
                    ),
                )
            ]
        ),
    )
    source = _generate(module)
    assert "annotated=False), [a[1], a[0]])" in source


def test_qif_body_register_operand_becomes_a_qubit_list(span: Span) -> None:
    """A whole-register operand is several wires once registers are gone, and
    a list is how Qiskit takes several qubits for one operand."""
    condition = QubitRef(name="c", size=1)
    target = QubitRef(name="out", size=2)
    module = IRModule(
        qubits=[condition, target],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[QubitBit(ref=condition, index=0)],
                    ctrl_state=1,
                    clause_ancillas=[],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(
                        ops=[GateOp(span=span, name="X", targets=[target])]
                    ),
                )
            ]
        ),
    )
    source = _generate(module)
    assert '_qif_body_1 = QuantumCircuit(2, name="qif_body")' in source
    assert "_qif_body_1.x([_qif_body_1.qubits[0], _qif_body_1.qubits[1]])" in source
    assert "annotated=False), [c[0], out[0], out[1]])" in source


def test_qif_multiple_clause_ancillas_compute_and_uncompute_in_order(
    span: Span,
) -> None:
    a = QubitRef(name="a", size=2)
    b = QubitRef(name="b", size=2)
    flag = QubitRef(name="flag", size=1)
    body_target = QubitRef(name="out", size=1)
    ancilla_a = QubitRef(name="_ancilla_0", size=1)
    ancilla_b = QubitRef(name="_ancilla_1", size=1)

    module = IRModule(
        qubits=[a, b, flag, body_target],
        body=IRBlock(
            ops=[
                QIfOp(
                    span=span,
                    direct_qubits=[
                        QubitBit(ref=ancilla_a, index=0),
                        QubitBit(ref=ancilla_b, index=0),
                        QubitBit(ref=flag, index=0),
                    ],
                    ctrl_state=0b111,
                    clause_ancillas=[
                        QIfClauseAncilla(qubits=[a], ctrl_state=2, ancilla=ancilla_a),
                        QIfClauseAncilla(qubits=[b], ctrl_state=3, ancilla=ancilla_b),
                    ],
                    negated=False,
                    ancilla=None,
                    body=IRBlock(
                        ops=[GateOp(span=span, name="X", targets=[body_target])]
                    ),
                )
            ]
        ),
    )
    source = _generate(module)

    compute_a = source.index("ctrl_state=2")
    compute_b = source.index("ctrl_state=3")
    final = source.index("ctrl_state=7")
    uncompute_b = source.index("ctrl_state=3", compute_b + 1)
    uncompute_a = source.index("ctrl_state=2", compute_a + 1)

    # Computed a, then b, then the final combination, then uncomputed in the
    # reverse order: b first, then a -- proper LIFO nesting.
    assert compute_a < compute_b < final < uncompute_b < uncompute_a


def test_arithmetic_op_renders_the_adder_call(span: Span) -> None:
    a = QubitRef(name="a", size=2)
    b = QubitRef(name="b", size=2)
    helper = QubitRef(name="_ancilla_0", size=1)
    module = IRModule(
        qubits=[a, b],
        body=IRBlock(
            ops=[
                ArithmeticOp(
                    span=span,
                    target=a,
                    addend=[b],
                    helper=helper,
                    subtract=False,
                    encode_constant=None,
                )
            ]
        ),
    )
    source = _generate(module)
    assert "from qiskit.circuit.library import CDKMRippleCarryAdder" in source
    assert (
        "circuit.append(CDKMRippleCarryAdder(2, kind='fixed'), "
        "[*b, *a, _ancilla_0[0]])" in source
    )


def test_arithmetic_op_subtract_uses_inverse(span: Span) -> None:
    a = QubitRef(name="a", size=2)
    b = QubitRef(name="b", size=2)
    helper = QubitRef(name="_ancilla_0", size=1)
    module = IRModule(
        qubits=[a, b],
        body=IRBlock(
            ops=[
                ArithmeticOp(
                    span=span,
                    target=a,
                    addend=[b],
                    helper=helper,
                    subtract=True,
                    encode_constant=None,
                )
            ]
        ),
    )
    source = _generate(module)
    assert (
        "circuit.append(CDKMRippleCarryAdder(2, kind='fixed').inverse(), "
        "[*b, *a, _ancilla_0[0]])" in source
    )


def test_arithmetic_op_pads_the_addend_with_an_ancilla(span: Span) -> None:
    a = QubitRef(name="a", size=3)
    b = QubitRef(name="b", size=2)
    padding = QubitRef(name="_ancilla_1", size=1)
    helper = QubitRef(name="_ancilla_0", size=1)
    module = IRModule(
        qubits=[a, b],
        body=IRBlock(
            ops=[
                ArithmeticOp(
                    span=span,
                    target=a,
                    addend=[b, padding],
                    helper=helper,
                    subtract=False,
                    encode_constant=None,
                )
            ]
        ),
    )
    source = _generate(module)
    assert (
        "circuit.append(CDKMRippleCarryAdder(3, kind='fixed'), "
        "[*b, *_ancilla_1, *a, _ancilla_0[0]])" in source
    )


def test_arithmetic_op_wider_addend_is_sliced(span: Span) -> None:
    a = QubitRef(name="a", size=2)
    b = QubitRef(name="b", size=3)
    helper = QubitRef(name="_ancilla_0", size=1)
    module = IRModule(
        qubits=[a, b],
        body=IRBlock(
            ops=[
                ArithmeticOp(
                    span=span,
                    target=a,
                    addend=[QubitSlice(ref=b, size=2)],
                    helper=helper,
                    subtract=False,
                    encode_constant=None,
                )
            ]
        ),
    )
    source = _generate(module)
    assert (
        "circuit.append(CDKMRippleCarryAdder(2, kind='fixed'), "
        "[*b[0:2], *a, _ancilla_0[0]])" in source
    )


def test_arithmetic_op_encodes_and_decodes_a_constant(span: Span) -> None:
    a = QubitRef(name="a", size=2)
    ancilla = QubitRef(name="_ancilla_1", size=2)
    helper = QubitRef(name="_ancilla_0", size=1)
    module = IRModule(
        qubits=[a],
        body=IRBlock(
            ops=[
                ArithmeticOp(
                    span=span,
                    target=a,
                    addend=[ancilla],
                    helper=helper,
                    subtract=False,
                    encode_constant=3,
                )
            ]
        ),
    )
    source = _generate(module)
    encode = source.index("circuit.x(_ancilla_1[0])")
    encode_bit1 = source.index("circuit.x(_ancilla_1[1])")
    adder_call = source.index("circuit.append(CDKMRippleCarryAdder")
    decode = source.index("circuit.x(_ancilla_1[0])", encode + 1)
    # Both bits of 3 (0b11) are encoded before the adder call, and the same
    # two X gates decode the ancilla back to |0> afterward.
    assert encode < encode_bit1 < adder_call < decode


def test_multiply_op_renders_the_multiplier_call(span: Span) -> None:
    a = QubitRef(name="a", size=2)
    b = QubitRef(name="b", size=2)
    c = QubitRef(name="c", size=4)
    helper = QubitRef(name="_ancilla_0", size=1)
    module = IRModule(
        qubits=[a, b, c],
        body=IRBlock(
            ops=[
                MultiplyOp(
                    span=span, left=[a], right=[b], product=c, helper=helper,
                    inverse=False,
                )
            ]
        ),
    )
    source = _generate(module)
    assert "from qiskit.circuit.library import HRSCumulativeMultiplier" in source
    assert (
        "circuit.append(HRSCumulativeMultiplier(2, num_result_qubits=4), "
        "[*a, *b, *c, _ancilla_0[0]])" in source
    )


def test_multiply_op_inverse_renders_the_reversed_multiplier(span: Span) -> None:
    a = QubitRef(name="a", size=2)
    b = QubitRef(name="b", size=2)
    temp = QubitRef(name="_ancilla_1", size=4)
    helper = QubitRef(name="_ancilla_0", size=1)
    module = IRModule(
        qubits=[a, b],
        body=IRBlock(
            ops=[
                MultiplyOp(
                    span=span, left=[a], right=[b], product=temp, helper=helper,
                    inverse=True,
                )
            ]
        ),
    )
    source = _generate(module)
    assert (
        "circuit.append(HRSCumulativeMultiplier(2, num_result_qubits=4).inverse(), "
        "[*a, *b, *_ancilla_1, _ancilla_0[0]])" in source
    )


def test_declare_ancilla_op_is_the_only_thing_that_declares(span: Span) -> None:
    """No operation declares the registers it uses: an operand says nothing
    about whether it has been brought into the circuit yet, and guessing that
    from the operand is how one register came to be declared twice."""
    ancilla = QubitRef(name="_ancilla_0", size=3)
    module = IRModule(
        body=IRBlock(ops=[DeclareAncillaOp(span=span, ref=ancilla)])
    )
    source = _generate(module)
    assert '_ancilla_0 = QuantumRegister(3, "_ancilla_0")' in source
    assert "circuit.add_register(_ancilla_0)" in source


def _generated_helper(name: str, call: str) -> Any:
    """The helper as the generated file itself defines it -- reached through a
    real compilation, so a missing import shows up here too."""
    result = compile_source(f"qbool q = false;\nRX({call}, q);\n", source_name="t.slanq")
    assert not result.diagnostics.has_errors
    assert result.qiskit_source is not None
    namespace: dict[str, Any] = {}
    exec(result.qiskit_source, namespace)  # noqa: S102
    return namespace[name]


@pytest.mark.parametrize(
    "value", [-4.0, -1.0, -0.25, 0.0, 0.25, 1.0, 2.0, 1e-12, 1e12, 1 + 2j, -1j]
)
def test_the_generated_sqrt_agrees_with_the_compile_time_one(
    value: float | complex,
) -> None:
    """Slanq's sqrt is not math.sqrt: a negative input gives a complex result,
    which an amplitude list may hold. The compiler evaluates one of these at
    compile time and the generated file the other, and nothing but this test
    keeps the two from drifting -- `math.sqrt(-1)` in a generated file raised
    at runtime for a program the compiler had accepted."""
    generated = _generated_helper("_sqrt", "sqrt(2)")
    assert generated(value) == _sqrt(value)
    assert type(generated(value)) is type(_sqrt(value))


@pytest.mark.parametrize(
    "value", [-2.5, -1.5, -0.5, 0.0, 0.5, 1.5, 2.5, 3.49, -3.49, 1e15 + 0.5]
)
def test_the_generated_round_agrees_with_the_compile_time_one(value: float) -> None:
    generated = _generated_helper("_round", "round(1.5)")
    assert generated(value) == _round_half_away(value)


def test_a_generated_sqrt_helper_brings_its_own_imports() -> None:
    result = compile_source("qbool q = false;\nRX(sqrt(2), q);\n", source_name="t.slanq")
    assert "import cmath" in result.qiskit_source
    assert "import math" in result.qiskit_source


def test_no_sqrt_helper_without_a_sqrt() -> None:
    result = compile_source("qbool q = false;\nRX(1.5, q);\n", source_name="t.slanq")
    assert "_sqrt" not in result.qiskit_source
    assert "import cmath" not in result.qiskit_source


def test_param_object_lines_for_scalar_and_array() -> None:
    module = IRModule(
        params=[
            ParamInfo(name="theta", kind="scalar", size=None, type_name="float"),
            ParamInfo(name="gamma", kind="array", size=3, type_name="int"),
        ]
    )
    source = _generate(module)
    assert "from qiskit.circuit import Parameter" in source
    assert 'theta = Parameter("theta")' in source
    assert 'gamma = [Parameter(f"gamma_{i}") for i in range(3)]' in source


def test_bound_circuit_binds_only_used_parameters() -> None:
    module = IRModule(
        params=[
            ParamInfo(name="theta", kind="scalar", size=None, type_name="float"),
            ParamInfo(name="gamma", kind="array", size=2, type_name="int"),
        ]
    )
    source = _generate(module)
    assert "def build_bound_circuit(theta: float, gamma: list[int]) -> QuantumCircuit:" in source
    assert '"theta": theta' in source
    assert '"gamma_0": gamma[0]' in source
    assert '"gamma_1": gamma[1]' in source
    assert "used = {parameter.name for parameter in circuit.parameters}" in source

    namespace: dict[str, object] = {}
    exec(source, namespace)  # noqa: S102
    bound = namespace["build_bound_circuit"](theta=1.0, gamma=[1, 2])
    assert bound.num_qubits == 0


def test_expression_renders_a_param_leaf(build_ast) -> None:
    ast = build_ast("param float theta;\nfloat r = theta * 2;")
    analyze(ast, DiagnosticBag())
    (_, use) = ast.statements
    rendered = _Generator().expression(use.initializer)
    assert rendered == "theta * 2"


def test_expression_renders_a_param_array_leaf(build_ast) -> None:
    ast = build_ast("param int gamma[4];\nfloat r = gamma[2];")
    analyze(ast, DiagnosticBag())
    (_, use) = ast.statements
    rendered = _Generator().expression(use.initializer)
    assert rendered == "gamma[2]"
