from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

from slanq.cli import main

EXAMPLES = Path(__file__).parent.parent / "examples"
MVP_A = str(EXAMPLES / "mvp_a.slanq")


def test_parse_prints_the_tree(capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["parse", MVP_A]) == 0
    assert "qbool_decl" in capsys.readouterr().out


def test_compile_writes_to_stdout(capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["compile", MVP_A]) == 0
    out = capsys.readouterr().out
    assert out.startswith("# Generated by Slanq ")
    assert "circuit.h(q[0])" in out


def test_compile_writes_to_file(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    destination = tmp_path / "out.py"
    assert main(["compile", MVP_A, "-o", str(destination)]) == 0
    assert capsys.readouterr().out == ""
    assert "def build_circuit()" in destination.read_text(encoding="utf-8")


def test_missing_file_reports_usage_error(capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["compile", str(EXAMPLES / "does_not_exist.slanq")]) == 2
    assert "Could not read file" in capsys.readouterr().err


def test_semantic_error_reports_compile_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    source = tmp_path / "bad.slanq"
    source.write_text("H(unknown);\n", encoding="utf-8")

    assert main(["compile", str(source)]) == 1
    assert "undefined name" in capsys.readouterr().err


def test_syntax_error_reports_compile_error(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    source = tmp_path / "bad.slanq"
    source.write_text("qbool q = ;\n", encoding="utf-8")

    assert main(["compile", str(source)]) == 1
    assert "Syntax error" in capsys.readouterr().err


def test_missing_command_exits_with_usage_error() -> None:
    with pytest.raises(SystemExit) as excinfo:
        main([])
    assert excinfo.value.code == 2


RUNNABLE_PROGRAMS = {
    "gates and measurement": (
        "qint<2> q = 0;\nH(q[0]);\nCX(q[0], q[1]);\nint result = measure(q);\n"
    ),
    "arithmetic": (
        "qint<3> a = 1;\nqint<2> b = 2;\na += b;\na -= 1;\n"
        "int result = measure(a);\n"
    ),
    "multiply accumulate": (
        "qint<2> a = 2;\nqint<2> b = 3;\nqint<4> c = 0;\nc += a * b;\n"
        "int result = measure(c);\n"
    ),
    "qif with a phase-only body": (
        "qint<2> a = 2;\nqif(a == 2) { phase(PI / 3); }\nint result = measure(a);\n"
    ),
    "qif with a negated condition": (
        "qint<2> a = 2;\nqbool t = false;\nqif(!(a == 2)) { X(t); }\n"
        "int result = measure(t);\n"
    ),
    "loop and process": (
        "process flip(qint x) { X(x); }\nqint<3> a = 0;\n"
        "for(int i in range(3)) { flip(a[i]); }\nint result = measure(a);\n"
    ),
    "superposition and helpers": (
        "qint<1> amp = {1 / sqrt(2), 1 / sqrt(2)};\nqbool q = false;\n"
        "RX(round(1.5) * PI / 4, q);\nint result = measure(amp);\n"
    ),
    "runtime parameters": (
        "param float theta;\nparam int gamma[2];\nqbool q = false;\n"
        "RX(theta + gamma[1], q);\nint result = measure(q);\n"
    ),
    "reset": (
        "qint<2> a = 3;\nH(a[1]);\nreset(a);\nX(a[0]);\n"
        "int result = measure(a);\n"
    ),
    "build-time branches": (
        "qint<3> a = 0;\nint n = 5;\nbool t = true;\n"
        "if (n > 9) { X(a[0]); } else if (n > 3) { X(a[1]); } else { H(a); }\n"
        "if (!t) { X(a[2]); }\n"
        "qif(a == 2) { if (t) { phase(PI / 3); } }\n"
        "int result = measure(a);\n"
    ),
}


@pytest.mark.slow
@pytest.mark.parametrize("program", sorted(RUNNABLE_PROGRAMS))
def test_the_generated_file_runs_in_a_fresh_interpreter(program: str) -> None:
    """Compiled through the command line into a file, then run the way a user
    runs it. Nothing here touches the project's own output directory: the file
    is written to a temporary one and deleted with it."""
    with tempfile.TemporaryDirectory() as directory:
        workspace = Path(directory)
        source = workspace / "program.slanq"
        source.write_text(RUNNABLE_PROGRAMS[program], encoding="utf-8")
        generated = workspace / "program_slanq.py"

        assert main(["compile", str(source), "-o", str(generated)]) == 0
        assert generated.exists()

        finished = subprocess.run(  # noqa: S603
            [sys.executable, str(generated)],
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=120,
            check=False,
        )

    assert finished.returncode == 0, finished.stderr
    assert finished.stdout.strip(), "the __main__ block prints the circuit"

