from __future__ import annotations

from slanq.ast_nodes import Span
from slanq.codegen import generate_qiskit
from slanq.ir import ClbitRef, GateOp, InitOp, IRBlock, IRModule, QubitBit, QubitRef


def _generate(module: IRModule) -> str:
    return generate_qiskit(module, source_name="mvp_a.slanq")


def test_output_is_valid_python(mvp_a_ir: IRModule) -> None:
    compile(_generate(mvp_a_ir), "<generated>", "exec")


def test_header_names_the_source(mvp_a_ir: IRModule) -> None:
    first_line = _generate(mvp_a_ir).splitlines()[0]
    assert first_line.startswith("# Generated by Slanq ")
    assert first_line.endswith(" from mvp_a.slanq")


def test_registers_and_circuit_are_declared(mvp_a_ir: IRModule) -> None:
    source = _generate(mvp_a_ir)
    assert 'q = QuantumRegister(1, "q")' in source
    assert 'result = ClassicalRegister(1, "result")' in source
    assert "circuit = QuantumCircuit(q, result)" in source


def test_gate_and_measurement_are_emitted(mvp_a_ir: IRModule) -> None:
    source = _generate(mvp_a_ir)
    assert "circuit.h(q[0])" in source
    assert "circuit.measure(q, result)" in source


def test_function_and_main_guard(mvp_a_ir: IRModule) -> None:
    source = _generate(mvp_a_ir)
    assert "def build_circuit() -> QuantumCircuit:" in source
    assert "return circuit" in source
    assert 'if __name__ == "__main__":' in source


def test_main_guard_forces_utf8_stdout(mvp_a_ir: IRModule) -> None:
    source = _generate(mvp_a_ir)
    assert "import sys" in source
    assert 'sys.stdout.reconfigure(encoding="utf-8")' in source


def test_false_initializer_emits_nothing(mvp_a_ir: IRModule) -> None:
    assert "circuit.x(" not in _generate(mvp_a_ir)


def test_true_initializer_emits_an_x_gate(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(ops=[InitOp(span=span, target=qubit, value=True)]),
    )
    assert "circuit.x(q[0])" in _generate(module)


def test_import_omits_classical_register_when_unused(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    module = IRModule(qubits=[qubit], body=IRBlock(ops=[]))
    source = _generate(module)
    assert "from qiskit import QuantumCircuit, QuantumRegister" in source
    assert "ClassicalRegister" not in source


def test_params_precede_targets(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[
                GateOp(
                    span=span,
                    name="RX",
                    targets=[QubitBit(ref=qubit, index=0)],
                    params=[90.0],
                )
            ]
        ),
    )
    assert "circuit.rx(90.0, q[0])" in _generate(module)


def test_whole_register_target_is_not_indexed(span: Span) -> None:
    qubit = QubitRef(name="a", size=3)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(ops=[GateOp(span=span, name="H", targets=[qubit])]),
    )
    assert "circuit.h(a)" in _generate(module)


def test_multi_qubit_constant_sets_the_right_bits(span: Span) -> None:
    """5 is 0b101; the register is little-endian, so bits 0 and 2 are flipped."""
    qubit = QubitRef(name="a", size=3)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(ops=[InitOp(span=span, target=qubit, value=5)]),
    )
    source = _generate(module)
    assert "circuit.x(a[0])" in source
    assert "circuit.x(a[2])" in source
    assert "circuit.x(a[1])" not in source


def test_index_is_mirrored_for_qiskit(span: Span) -> None:
    """Slanq's q[0] is the most significant qubit, Qiskit's q[0] the least."""
    qubit = QubitRef(name="q", size=3)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[GateOp(span=span, name="H", targets=[QubitBit(ref=qubit, index=0)])]
        ),
    )
    assert "circuit.h(q[2])" in _generate(module)


def test_single_qubit_register_needs_no_mirroring(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    module = IRModule(
        qubits=[qubit],
        body=IRBlock(
            ops=[GateOp(span=span, name="H", targets=[QubitBit(ref=qubit, index=0)])]
        ),
    )
    assert "circuit.h(q[0])" in _generate(module)


def test_generated_module_builds_a_runnable_circuit(mvp_a_ir: IRModule) -> None:
    namespace: dict[str, object] = {}
    exec(_generate(mvp_a_ir), namespace)  # noqa: S102
    circuit = namespace["build_circuit"]()
    assert circuit.num_qubits == 1
    assert circuit.num_clbits == 1


def test_unused_clbit_register_still_declared(span: Span) -> None:
    qubit = QubitRef(name="q", size=1)
    clbit = ClbitRef(name="result", size=1)
    module = IRModule(qubits=[qubit], clbits=[clbit], body=IRBlock(ops=[]))
    assert 'result = ClassicalRegister(1, "result")' in _generate(module)
