from __future__ import annotations

import math
from typing import cast

from slanq import __version__
from slanq.ast_nodes import (
    BinaryOp,
    Call,
    ClassicalDecl,
    Expression,
    Index,
    Literal,
    Name,
    ParamArrayDecl,
    ParamDecl,
    UnaryOp,
)
from slanq.builtin import BUILTIN_CONSTANTS, BUILTIN_FUNCTIONS, const_int
from slanq.diagnostics import SlanqError
from slanq.ir import (
    ArithmeticOp,
    DeclareAncillaOp,
    GateOp,
    InitOp,
    IRBlock,
    IRModule,
    MeasurementOp,
    MultiplyOp,
    Op,
    ParamInfo,
    PhaseOp,
    QIfOp,
    QubitBit,
    QubitOperand,
    QubitRef,
    QubitSlice,
)

INDENT = " " * 4

# A physical qubit as (register name, Qiskit index), and a renaming of such
# qubits to their wires in a nested sub-circuit.
Qubit = tuple[str, int]
QubitMap = dict[Qubit, str]

BINARY_PRECEDENCE: dict[str, int] = {
    "|": 1, "^": 2, "&": 3,
    "+": 4, "-": 4,
    "*": 5, "/": 5, "%": 5,
    "**": 7,
}
UNARY_PRECEDENCE = 6
ATOM_PRECEDENCE = 99

PYTHON_CONSTANTS: dict[str, str] = {"PI": "np.pi"}

# Lower-casing the Slanq name happens to work for every gate today, but it
# would silently emit `circuit.phase(...)` -- a method Qiskit does not have --
# for anything whose Qiskit spelling differs. An explicit table fails loudly
# instead, the same guard as the transformer's __default__.
QISKIT_METHODS: dict[str, str] = {
    "H": "h", "X": "x", "Y": "y", "Z": "z", "S": "s", "T": "t",
    "Sdg": "sdg", "Tdg": "tdg",
    "RX": "rx", "RY": "ry", "RZ": "rz",
    "CX": "cx", "CY": "cy", "CZ": "cz", "CH": "ch", "SWAP": "swap", "CCX": "ccx",
}

# Two of these are not Python's. Slanq rounds a half away from zero, Python to
# even; and Slanq's sqrt takes a negative input to a complex result, which an
# amplitude list may legitimately hold, while math.sqrt raises there. Both are
# emitted as helpers so the generated file computes what the compiler did.
PYTHON_FUNCTIONS: dict[str, str] = {
    "floor": "math.floor",
    "ceil": "math.ceil",
    "round": "_round",
    "sqrt": "_sqrt",
}

# Matches analysis.py's NORMALIZATION_TOLERANCE: below this, a `{}` amplitude
# list is close enough to already-normalized that its elements can be
# rendered as the original expressions, not divided by a computed norm.
AMPLITUDE_NORMALIZATION_TOLERANCE = 1e-9

ROUND_HELPER = [
    "def _round(value: float) -> int:",
    INDENT + '"""Slanq rounds a half away from zero; Python\'s round() rounds to even."""',
    INDENT + "return math.floor(value + 0.5) if value >= 0 else math.ceil(value - 0.5)",
]

SQRT_HELPER = [
    "def _sqrt(value: float | complex) -> float | complex:",
    INDENT + '"""A negative real or complex input promotes to a complex result',
    INDENT + '(with the expected i); a nonnegative real input stays a float."""',
    INDENT + "if isinstance(value, complex) or value < 0:",
    INDENT * 2 + "return cmath.sqrt(value)",
    INDENT + "return math.sqrt(value)",
]


def generate_qiskit(module: IRModule, *, source_name: str) -> str:
    generator = _Generator()
    body = generator.body_lines(module)

    lines = [
        f"# Generated by Slanq {__version__} from {source_name}",
        "# Do not edit: changes are lost on regeneration.",
        "",
    ]
    lines += generator.import_lines(module)
    if generator.needs_round:
        lines += ["", ""] + ROUND_HELPER
    if generator.needs_sqrt:
        lines += ["", ""] + SQRT_HELPER
    if module.params:
        lines += ["", ""] + _param_object_lines(module)
    lines += [
        "",
        "",
        "def build_circuit() -> QuantumCircuit:",
    ]
    lines += [INDENT + line for line in body]
    if module.params:
        lines += ["", ""] + _bound_circuit_lines(module)
    lines += [
        "",
        "",
        'if __name__ == "__main__":',
        # The circuit drawing uses box-drawing characters, which fail on a
        # non-UTF-8 stdout (Windows consoles, redirected output). Guarded:
        # `reconfigure` is a TextIOWrapper method, missing if something else
        # already replaced sys.stdout (Jupyter %run, IDLE).
        INDENT + 'if hasattr(sys.stdout, "reconfigure"):',
        INDENT * 2 + 'sys.stdout.reconfigure(encoding="utf-8")',
        INDENT + "print(build_circuit())",
        "",
    ]
    return "\n".join(lines)


def _array_size(param: ParamInfo) -> int:
    assert param.size is not None
    return param.size


def _param_object_lines(module: IRModule) -> list[str]:
    lines = []
    for param in module.params:
        if param.kind == "scalar":
            lines.append(f'{param.name} = Parameter("{param.name}")')
        else:
            lines.append(
                f'{param.name} = [Parameter(f"{param.name}_{{i}}") '
                f"for i in range({_array_size(param)})]"
            )
    return lines


def _bound_circuit_lines(module: IRModule) -> list[str]:
    """A convenience wrapper around `build_circuit()`: it binds every
    declared `param` by name, skipping any that turned out unused -- Qiskit
    refuses to bind a name absent from the circuit."""
    parameters = ", ".join(
        f"{param.name}: {param.type_name}"
        if param.kind == "scalar"
        else f"{param.name}: list[{param.type_name}]"
        for param in module.params
    )
    bindings = ", ".join(
        f'"{param.name}": {param.name}'
        if param.kind == "scalar"
        else ", ".join(
            f'"{param.name}_{i}": {param.name}[{i}]' for i in range(_array_size(param))
        )
        for param in module.params
    )
    return [
        f"def build_bound_circuit({parameters}) -> QuantumCircuit:",
        INDENT + "circuit = build_circuit()",
        INDENT + f"bindings = {{{bindings}}}",
        INDENT + "used = {parameter.name for parameter in circuit.parameters}",
        INDENT + "return circuit.assign_parameters(",
        INDENT * 2 + "{name: value for name, value in bindings.items() if name in used}",
        INDENT + ")",
    ]


class _Generator:
    """Renders one module. The imports depend on what the body turned out to
    need, so the body is rendered first and the header assembled afterwards."""

    def __init__(self) -> None:
        self.needs_numpy = False
        self.needs_math = False
        self.needs_round = False
        self.needs_sqrt = False
        self.needs_state_preparation = False
        self.needs_xgate = False
        self.needs_cdkm_adder = False
        self.needs_hrs_multiplier = False
        self._qif_counter = 0

    def import_lines(self, module: IRModule) -> list[str]:
        standard = ["import sys"]
        if self.needs_math or self.needs_round or self.needs_sqrt:
            standard.insert(0, "import math")
        if self.needs_sqrt:
            standard.insert(0, "import cmath")

        qiskit_names = ["QuantumCircuit", "QuantumRegister"]
        if module.clbits:
            qiskit_names.append("ClassicalRegister")
        third_party = [f"from qiskit import {', '.join(sorted(qiskit_names))}"]
        if module.params:
            third_party.append("from qiskit.circuit import Parameter")

        library_names = []
        if self.needs_state_preparation:
            library_names.append("StatePreparation")
        if self.needs_xgate:
            library_names.append("XGate")
        if self.needs_cdkm_adder:
            library_names.append("CDKMRippleCarryAdder")
        if self.needs_hrs_multiplier:
            library_names.append("HRSCumulativeMultiplier")
        if library_names:
            third_party.append(
                f"from qiskit.circuit.library import {', '.join(sorted(library_names))}"
            )

        if self.needs_numpy:
            third_party.insert(0, "import numpy as np")

        return standard + [""] + third_party

    def body_lines(self, module: IRModule) -> list[str]:
        lines = [
            f'{ref.name} = QuantumRegister({ref.size}, "{ref.name}")' for ref in module.qubits
        ]
        lines += [
            f'{ref.name} = ClassicalRegister({ref.size}, "{ref.name}")' for ref in module.clbits
        ]

        registers = [ref.name for ref in module.qubits] + [ref.name for ref in module.clbits]
        lines.append(f"circuit = QuantumCircuit({', '.join(registers)})")

        for op in module.body.ops:
            lines += self.op_lines(op)

        lines.append("return circuit")
        return lines

    def op_lines(
        self,
        op: Op,
        circuit_var: str = "circuit",
        qubits: QubitMap | None = None,
    ) -> list[str]:
        """`qubits` renames every physical qubit to its wire in a nested
        sub-circuit; only a qif body passes one."""
        if isinstance(op, InitOp):
            if isinstance(op.value, list):
                return self._state_preparation_lines(op, circuit_var)
            # The register is little-endian, so bit b of the value sits on qubit b.
            # Unlike an explicit index, this needs no mirroring.
            return [
                f"{circuit_var}.x({op.target.name}[{bit}])"
                for bit in range(op.target.size)
                if (int(op.value) >> bit) & 1
            ]

        if isinstance(op, GateOp):
            method = QISKIT_METHODS.get(op.name)
            if method is None:
                raise SlanqError(
                    f"internal error: no Qiskit method for the gate '{op.name}'. "
                    "This is a bug in the compiler, not in the source program."
                )
            arguments = [self.expression(param) for param in op.params]
            arguments += [_target_source(target, qubits) for target in op.targets]
            return [f"{circuit_var}.{method}({', '.join(arguments)})"]

        if isinstance(op, MeasurementOp):
            return [
                f"{circuit_var}.measure({_operand_source(op.source)}, {op.target.name})"
            ]

        if isinstance(op, PhaseOp):
            return [f"{circuit_var}.global_phase += {self.expression(op.angle)}"]

        if isinstance(op, QIfOp):
            return self._qif_lines(op, circuit_var)

        if isinstance(op, ArithmeticOp):
            return self._arithmetic_lines(op, circuit_var)

        if isinstance(op, MultiplyOp):
            return self._multiply_lines(op, circuit_var)

        if isinstance(op, DeclareAncillaOp):
            return [
                f'{op.ref.name} = QuantumRegister({op.ref.size}, "{op.ref.name}")',
                f"{circuit_var}.add_register({op.ref.name})",
            ]

        raise NotImplementedError(f"no code generation for {type(op).__name__}")

    def _arithmetic_lines(self, op: ArithmeticOp, circuit_var: str) -> list[str]:
        lines: list[str] = []

        constant_ancilla: QubitRef | None = None
        encode_bits: list[int] = []
        if op.encode_constant is not None:
            (addend_ancilla,) = op.addend
            assert isinstance(addend_ancilla, QubitRef)
            constant_ancilla = addend_ancilla
            encode_bits = [
                bit
                for bit in range(constant_ancilla.size)
                if (op.encode_constant >> bit) & 1
            ]
            for bit in encode_bits:
                lines.append(f"{circuit_var}.x({constant_ancilla.name}[{bit}])")

        self.needs_cdkm_adder = True
        adder = f"CDKMRippleCarryAdder({op.target.size}, kind='fixed')"
        gate = f"{adder}.inverse()" if op.subtract else adder
        qubits = ", ".join(
            [
                *(_spread_source(operand) for operand in op.addend),
                _spread_source(op.target),
                f"{op.helper.name}[0]",
            ]
        )
        lines.append(f"{circuit_var}.append({gate}, [{qubits}])")

        if constant_ancilla is not None:
            for bit in encode_bits:
                lines.append(f"{circuit_var}.x({constant_ancilla.name}[{bit}])")

        return lines

    def _multiply_lines(self, op: MultiplyOp, circuit_var: str) -> list[str]:
        lines: list[str] = []
        self.needs_hrs_multiplier = True
        width = sum(_operand_width(operand) for operand in op.left)
        multiplier = (
            f"HRSCumulativeMultiplier({width}, num_result_qubits={op.product.size})"
        )
        gate = f"{multiplier}.inverse()" if op.inverse else multiplier
        qubits = ", ".join(
            [
                *(_spread_source(operand) for operand in op.left),
                *(_spread_source(operand) for operand in op.right),
                _spread_source(op.product),
                f"{op.helper.name}[0]",
            ]
        )
        lines.append(f"{circuit_var}.append({gate}, [{qubits}])")
        return lines

    def _state_preparation_lines(self, op: InitOp, circuit_var: str) -> list[str]:
        assert isinstance(op.value, list)
        values = op.value

        if not values:
            return [
                f"{circuit_var}.h({op.target.name}[{bit}])"
                for bit in range(op.target.size)
            ]

        self.needs_state_preparation = True
        if op.is_amplitude:
            norm_squared = sum(abs(value) ** 2 for value in values)
            already_normalized = abs(norm_squared - 1.0) <= AMPLITUDE_NORMALIZATION_TOLERANCE
            if op.value_expressions is not None and already_normalized:
                rendered = ", ".join(self.expression(e) for e in op.value_expressions)
                return [
                    f"{circuit_var}.append(StatePreparation([{rendered}]), {op.target.name})"
                ]
            norm = math.sqrt(norm_squared)
            amplitudes = [value / norm for value in values]
        else:
            probabilities = cast(list[float], values)
            total = sum(probabilities)
            amplitudes = [math.sqrt(probability / total) for probability in probabilities]
        rendered = ", ".join(repr(amplitude) for amplitude in amplitudes)
        return [f"{circuit_var}.append(StatePreparation([{rendered}]), {op.target.name})"]

    def _qif_lines(self, op: QIfOp, circuit_var: str) -> list[str]:
        # A global phase gets no wire in the sub-circuit, because controlling
        # one is exactly a phase gate on the control qubits themselves. A body
        # made only of phases therefore needs no sub-circuit at all.
        phases = [sub_op for sub_op in op.body.ops if isinstance(sub_op, PhaseOp)]
        gates = [sub_op for sub_op in op.body.ops if not isinstance(sub_op, PhaseOp)]
        if not phases and not gates:
            return []

        lines: list[str] = []
        body_var = ""
        body_sources: list[str] = []
        if gates:
            self._qif_counter += 1
            body_var = f"_qif_body_{self._qif_counter}"

            # The sub-circuit gets one wire per qubit the body actually
            # touches, never a whole register: a register would drag in its
            # untouched qubits too, and if one of those is a condition qubit
            # it would then appear twice in the append list below --
            # `CircuitError: duplicate bit arguments` at generated-file
            # runtime, for a program whose condition and body do touch
            # different qubits (`qif(a[0]) { X(a[1]); }`).
            body_qubits = _body_qubits(op.body)
            local = {
                qubit: f"{body_var}.qubits[{wire}]"
                for wire, qubit in enumerate(body_qubits)
            }
            lines.append(
                f'{body_var} = QuantumCircuit({len(body_qubits)}, name="qif_body")'
            )
            for sub_op in gates:
                lines += self.op_lines(sub_op, body_var, qubits=local)
            body_sources = [f"{name}[{index}]" for name, index in body_qubits]

        angle = (
            " + ".join(
                self._wrapped(phase.angle, BINARY_PRECEDENCE["+"]) for phase in phases
            )
            if phases
            else None
        )

        # Each wide-negated clause needs its own ancilla, computed before
        # everything else and uncomputed after everything else -- proper
        # last-in-first-out nesting, like any compute/uncompute pair.
        clause_computes: list[tuple[str, str]] = []
        for clause_ancilla in op.clause_ancillas:
            self.needs_xgate = True
            name = clause_ancilla.ancilla.name
            clause_sources = [_spread_source(q) for q in clause_ancilla.qubits]
            clause_controls = sum(_operand_width(q) for q in clause_ancilla.qubits)
            compute = (
                f"XGate().control({clause_controls}, "
                f"ctrl_state={clause_ancilla.ctrl_state}, annotated=False)"
            )
            compute_qubits = ", ".join([*clause_sources, f"{name}[0]"])
            lines.append(f"{circuit_var}.append({compute}, [{compute_qubits}])")
            lines.append(f"{circuit_var}.x({name}[0])")
            clause_computes.append((compute, compute_qubits))

        condition_sources = [_spread_source(entry) for entry in op.direct_qubits]
        total_controls = sum(_operand_width(entry) for entry in op.direct_qubits)

        if not op.negated:
            lines += self._controlled_body_lines(
                circuit_var,
                controls=condition_sources,
                control_bits=[
                    bit for entry in op.direct_qubits for bit in _operand_bits(entry)
                ],
                ctrl_state=op.ctrl_state,
                body_var=body_var,
                body_sources=body_sources,
                angle=angle,
            )
        else:
            # Negated, spanning more than one qubit: compute the positive
            # match into a fresh ancilla, flip it, run the body controlled by
            # just that one ancilla, flip back, and uncompute.
            self.needs_xgate = True
            assert op.ancilla is not None
            ancilla = op.ancilla.name
            compute = (
                f"XGate().control({total_controls}, ctrl_state={op.ctrl_state}, "
                "annotated=False)"
            )
            compute_qubits = ", ".join([*condition_sources, f"{ancilla}[0]"])
            lines.append(f"{circuit_var}.append({compute}, [{compute_qubits}])")
            lines.append(f"{circuit_var}.x({ancilla}[0])")

            lines += self._controlled_body_lines(
                circuit_var,
                controls=[f"{ancilla}[0]"],
                control_bits=[f"{ancilla}[0]"],
                ctrl_state=1,
                body_var=body_var,
                body_sources=body_sources,
                angle=angle,
            )

            lines.append(f"{circuit_var}.x({ancilla}[0])")
            lines.append(f"{circuit_var}.append({compute}, [{compute_qubits}])")

        # Uncompute the clause ancillas in reverse order.
        for clause_ancilla, (compute, compute_qubits) in zip(
            reversed(op.clause_ancillas), reversed(clause_computes), strict=True
        ):
            name = clause_ancilla.ancilla.name
            lines.append(f"{circuit_var}.x({name}[0])")
            lines.append(f"{circuit_var}.append({compute}, [{compute_qubits}])")

        return lines

    def _controlled_body_lines(
        self,
        circuit_var: str,
        *,
        controls: list[str],
        control_bits: list[str],
        ctrl_state: int,
        body_var: str,
        body_sources: list[str],
        angle: str | None,
    ) -> list[str]:
        """The body under one control set: its gates as a controlled
        sub-circuit, its phase as a phase gate on the controls themselves.
        `control_bits` is that same control set one qubit at a time, which a
        phase gate needs and a spread whole-register operand cannot give.

        The phase is emitted after the gates whatever order the body was
        written in. A phase commutes with exactly those operators that map the
        set of states its condition matches onto itself; anything else would
        have to move amplitude across that line, which takes a condition qubit
        as a target. A qif body may not touch its own condition, so nothing in
        one can. Loosening that rule breaks this."""
        lines: list[str] = []
        if body_sources:
            controlled = (
                f"{body_var}.to_gate().control({len(control_bits)}, "
                f"ctrl_state={ctrl_state}, annotated=False)"
            )
            qubits = ", ".join([*controls, *body_sources])
            lines.append(f"{circuit_var}.append({controlled}, [{qubits}])")

        if angle is None:
            return lines

        # A phase gate fires on |1...1>, so a control the condition wants at
        # zero is conjugated into that basis first.
        zeros = [
            bit
            for position, bit in enumerate(control_bits)
            if not (ctrl_state >> position) & 1
        ]
        lines += [f"{circuit_var}.x({bit})" for bit in zeros]
        if len(control_bits) == 1:
            lines.append(f"{circuit_var}.p({angle}, {control_bits[0]})")
        else:
            rest = ", ".join(control_bits[:-1])
            lines.append(f"{circuit_var}.mcp({angle}, [{rest}], {control_bits[-1]})")
        lines += [f"{circuit_var}.x({bit})" for bit in zeros]
        return lines

    def expression(self, expression: Expression) -> str:
        if isinstance(expression, Literal):
            return repr(expression.value)

        if isinstance(expression, Name) and expression.name in BUILTIN_CONSTANTS:
            self.needs_numpy = True
            return PYTHON_CONSTANTS[expression.name]

        if isinstance(expression, Name) and isinstance(
            expression.resolved_symbol, ParamDecl
        ):
            return expression.name

        if isinstance(expression, Name) and isinstance(
            expression.resolved_symbol, ClassicalDecl
        ):
            # No Python variable exists for a classical constant (lowering
            # gives it no IR representation) -- inline its initializer, same
            # substitution const_value already does for compile-time eval.
            return self.expression(expression.resolved_symbol.initializer)

        if isinstance(expression, Index) and isinstance(
            expression.base.resolved_symbol, ParamArrayDecl
        ):
            index = const_int(expression.index)
            return f"{expression.base.name}[{index}]"

        if isinstance(expression, UnaryOp) and expression.op in ("-", "~"):
            return f"{expression.op}{self._wrapped(expression.operand, UNARY_PRECEDENCE)}"

        if isinstance(expression, BinaryOp) and expression.op in BINARY_PRECEDENCE:
            return self._binary(expression)

        if isinstance(expression, Call) and expression.callee.name in BUILTIN_FUNCTIONS:
            return self._call(expression)

        raise SlanqError(
            f"internal error: {type(expression).__name__} cannot be rendered as Python. "
            "This is a bug in the compiler, not in the source program."
        )

    def _binary(self, expression: BinaryOp) -> str:
        precedence = BINARY_PRECEDENCE[expression.op]
        right_associative = expression.op == "**"
        left = self._wrapped(expression.left, precedence + int(right_associative))
        right = self._wrapped(expression.right, precedence + int(not right_associative))
        return f"{left} {expression.op} {right}"

    def _call(self, expression: Call) -> str:
        name = expression.callee.name
        if name == "round":
            self.needs_round = True
        elif name == "sqrt":
            self.needs_sqrt = True
        else:
            self.needs_math = True
        rendered = ", ".join(self.expression(argument) for argument in expression.args)
        return f"{PYTHON_FUNCTIONS[name]}({rendered})"

    def _wrapped(self, expression: Expression, minimum: int) -> str:
        rendered = self.expression(expression)
        return f"({rendered})" if _precedence(expression) < minimum else rendered


def _precedence(expression: Expression) -> int:
    if isinstance(expression, BinaryOp):
        return BINARY_PRECEDENCE.get(expression.op, ATOM_PRECEDENCE)
    if isinstance(expression, UnaryOp):
        return UNARY_PRECEDENCE
    return ATOM_PRECEDENCE


def _operand_source(operand: QubitOperand) -> str:
    if isinstance(operand, QubitBit):
        return f"{operand.ref.name}[{_qiskit_index(operand)}]"
    assert not isinstance(operand, QubitSlice)
    return operand.name


def _spread_source(operand: QubitOperand) -> str:
    """Every qubit of `operand`, unpacked in place inside a `[...]` argument
    list -- value semantics, no mirroring, same rule as `_operand_source`'s
    whole-register case."""
    if isinstance(operand, QubitBit):
        return _operand_source(operand)
    if isinstance(operand, QubitSlice):
        return f"*{operand.ref.name}[0:{operand.size}]"
    return f"*{operand.name}"


def _operand_width(operand: QubitOperand) -> int:
    return 1 if isinstance(operand, QubitBit) else operand.size


def _operand_bits(operand: QubitOperand) -> list[str]:
    """`operand` as one source per qubit, in the same order `_spread_source`
    unpacks it in."""
    if isinstance(operand, QubitBit):
        return [_operand_source(operand)]
    name = operand.ref.name if isinstance(operand, QubitSlice) else operand.name
    return [f"{name}[{index}]" for index in range(operand.size)]


def _qiskit_index(bit: QubitBit) -> int:
    """Slanq indexes big-endian -- index 0 is the most significant qubit --
    while the Qiskit register is little-endian."""
    return bit.ref.size - 1 - bit.index


def _body_qubits(body: IRBlock) -> list[Qubit]:
    """Every physical qubit a qif body's gates touch, in first-reference
    order -- one wire each in the sub-circuit, and, in this same order, the
    tail of the qubit list passed to circuit.append()."""
    seen: dict[Qubit, None] = {}
    for op in body.ops:
        if isinstance(op, PhaseOp):
            continue  # a global phase touches no qubit
        assert isinstance(op, GateOp), (
            "a qif body holds only gates and phases; a new op kind allowed "
            "here must have its operands mapped into the sub-circuit too"
        )
        for target in op.targets:
            for qubit in _operand_qubits(target):
                seen[qubit] = None
    return list(seen)


def _operand_qubits(operand: QubitOperand) -> list[Qubit]:
    """`operand` spread into physical qubits. A whole register contributes all
    of its qubits in Qiskit order -- the order Qiskit broadcasts it in."""
    if isinstance(operand, QubitBit):
        return [(operand.ref.name, _qiskit_index(operand))]
    assert not isinstance(operand, QubitSlice), "a qif body has no sliced operands"
    return [(operand.name, index) for index in range(operand.size)]


def _target_source(operand: QubitOperand, qubits: QubitMap | None) -> str:
    if qubits is None:
        return _operand_source(operand)
    sources = [qubits[qubit] for qubit in _operand_qubits(operand)]
    # A list is how Qiskit takes several qubits for one operand, which is what
    # a whole-register operand becomes once registers are gone.
    return sources[0] if len(sources) == 1 else f"[{', '.join(sources)}]"


__all__ = ["generate_qiskit"]
