from __future__ import annotations

import math

from slanq import __version__
from slanq.ast_nodes import (
    BinaryOp,
    Call,
    Expression,
    Index,
    Literal,
    Name,
    ParamArrayDecl,
    ParamDecl,
    UnaryOp,
)
from slanq.builtin import BUILTIN_CONSTANTS, BUILTIN_FUNCTIONS, const_int
from slanq.diagnostics import SlanqError
from slanq.ir import (
    ArithmeticOp,
    GateOp,
    InitOp,
    IRBlock,
    IRModule,
    MeasurementOp,
    MultiplyOp,
    Op,
    ParamInfo,
    PhaseOp,
    QIfOp,
    QubitBit,
    QubitOperand,
    QubitRef,
    QubitSlice,
)

INDENT = " " * 4

BINARY_PRECEDENCE: dict[str, int] = {
    "|": 1, "^": 2, "&": 3,
    "+": 4, "-": 4,
    "*": 5, "/": 5, "%": 5,
    "**": 7,
}
UNARY_PRECEDENCE = 6
ATOM_PRECEDENCE = 99

PYTHON_CONSTANTS: dict[str, str] = {"PI": "np.pi"}

# Lower-casing the Slanq name happens to work for every gate today, but it
# would silently emit `circuit.phase(...)` -- a method Qiskit does not have --
# for anything whose Qiskit spelling differs. An explicit table fails loudly
# instead, the same guard as the transformer's __default__.
QISKIT_METHODS: dict[str, str] = {
    "H": "h", "X": "x", "Y": "y", "Z": "z", "S": "s", "T": "t",
    "Sdg": "sdg", "Tdg": "tdg",
    "RX": "rx", "RY": "ry", "RZ": "rz",
    "CX": "cx", "CY": "cy", "CZ": "cz", "CH": "ch", "SWAP": "swap", "CCX": "ccx",
}

# `round` is not Python's: Slanq rounds a half away from zero, Python to even.
PYTHON_FUNCTIONS: dict[str, str] = {
    "floor": "math.floor",
    "ceil": "math.ceil",
    "round": "_round",
}

ROUND_HELPER = [
    "def _round(value: float) -> int:",
    INDENT + '"""Slanq rounds a half away from zero; Python\'s round() rounds to even."""',
    INDENT + "return math.floor(value + 0.5) if value >= 0 else math.ceil(value - 0.5)",
]


def generate_qiskit(module: IRModule, *, source_name: str) -> str:
    generator = _Generator()
    body = generator.body_lines(module)

    lines = [
        f"# Generated by Slanq {__version__} from {source_name}",
        "# Do not edit: changes are lost on regeneration.",
        "",
    ]
    lines += generator.import_lines(module)
    if generator.needs_round:
        lines += ["", ""] + ROUND_HELPER
    if module.params:
        lines += ["", ""] + _param_object_lines(module)
    lines += [
        "",
        "",
        "def build_circuit() -> QuantumCircuit:",
    ]
    lines += [INDENT + line for line in body]
    if module.params:
        lines += ["", ""] + _bound_circuit_lines(module)
    lines += [
        "",
        "",
        'if __name__ == "__main__":',
        # The circuit drawing uses box-drawing characters, which fail on a
        # non-UTF-8 stdout (Windows consoles, redirected output).
        INDENT + 'sys.stdout.reconfigure(encoding="utf-8")',
        INDENT + "print(build_circuit())",
        "",
    ]
    return "\n".join(lines)


def _array_size(param: ParamInfo) -> int:
    assert param.size is not None
    return param.size


def _param_object_lines(module: IRModule) -> list[str]:
    lines = []
    for param in module.params:
        if param.kind == "scalar":
            lines.append(f'{param.name} = Parameter("{param.name}")')
        else:
            lines.append(
                f'{param.name} = [Parameter(f"{param.name}_{{i}}") '
                f"for i in range({_array_size(param)})]"
            )
    return lines


def _bound_circuit_lines(module: IRModule) -> list[str]:
    """A convenience wrapper around `build_circuit()`: it binds every
    declared `param` by name, skipping any that turned out unused -- Qiskit
    refuses to bind a name absent from the circuit."""
    parameters = ", ".join(
        f"{param.name}: {param.type_name}"
        if param.kind == "scalar"
        else f"{param.name}: list[{param.type_name}]"
        for param in module.params
    )
    bindings = ", ".join(
        f'"{param.name}": {param.name}'
        if param.kind == "scalar"
        else ", ".join(
            f'"{param.name}_{i}": {param.name}[{i}]' for i in range(_array_size(param))
        )
        for param in module.params
    )
    return [
        f"def build_bound_circuit({parameters}) -> QuantumCircuit:",
        INDENT + "circuit = build_circuit()",
        INDENT + f"bindings = {{{bindings}}}",
        INDENT + "used = {parameter.name for parameter in circuit.parameters}",
        INDENT + "return circuit.assign_parameters(",
        INDENT * 2 + "{name: value for name, value in bindings.items() if name in used}",
        INDENT + ")",
    ]


class _Generator:
    """Renders one module. The imports depend on what the body turned out to
    need, so the body is rendered first and the header assembled afterwards."""

    def __init__(self) -> None:
        self.needs_numpy = False
        self.needs_math = False
        self.needs_round = False
        self.needs_state_preparation = False
        self.needs_xgate = False
        self.needs_cdkm_adder = False
        self.needs_hrs_multiplier = False
        self._qif_counter = 0

    def import_lines(self, module: IRModule) -> list[str]:
        standard = ["import sys"]
        if self.needs_math or self.needs_round:
            standard.insert(0, "import math")

        qiskit_names = ["QuantumCircuit", "QuantumRegister"]
        if module.clbits:
            qiskit_names.append("ClassicalRegister")
        third_party = [f"from qiskit import {', '.join(sorted(qiskit_names))}"]
        if module.params:
            third_party.append("from qiskit.circuit import Parameter")

        library_names = []
        if self.needs_state_preparation:
            library_names.append("StatePreparation")
        if self.needs_xgate:
            library_names.append("XGate")
        if self.needs_cdkm_adder:
            library_names.append("CDKMRippleCarryAdder")
        if self.needs_hrs_multiplier:
            library_names.append("HRSCumulativeMultiplier")
        if library_names:
            third_party.append(
                f"from qiskit.circuit.library import {', '.join(sorted(library_names))}"
            )

        if self.needs_numpy:
            third_party.insert(0, "import numpy as np")

        return standard + [""] + third_party

    def body_lines(self, module: IRModule) -> list[str]:
        lines = [
            f'{ref.name} = QuantumRegister({ref.size}, "{ref.name}")' for ref in module.qubits
        ]
        lines += [
            f'{ref.name} = ClassicalRegister({ref.size}, "{ref.name}")' for ref in module.clbits
        ]

        registers = [ref.name for ref in module.qubits] + [ref.name for ref in module.clbits]
        lines.append(f"circuit = QuantumCircuit({', '.join(registers)})")

        for op in module.body.ops:
            lines += self.op_lines(op)

        lines.append("return circuit")
        return lines

    def op_lines(self, op: Op, circuit_var: str = "circuit") -> list[str]:
        if isinstance(op, InitOp):
            if isinstance(op.value, list):
                return self._state_preparation_lines(op, circuit_var)
            # The register is little-endian, so bit b of the value sits on qubit b.
            # Unlike an explicit index, this needs no mirroring.
            return [
                f"{circuit_var}.x({op.target.name}[{bit}])"
                for bit in range(op.target.size)
                if (int(op.value) >> bit) & 1
            ]

        if isinstance(op, GateOp):
            method = QISKIT_METHODS.get(op.name)
            if method is None:
                raise SlanqError(
                    f"internal error: no Qiskit method for the gate '{op.name}'. "
                    "This is a bug in the compiler, not in the source program."
                )
            arguments = [self.expression(param) for param in op.params]
            arguments += [_operand_source(target) for target in op.targets]
            return [f"{circuit_var}.{method}({', '.join(arguments)})"]

        if isinstance(op, MeasurementOp):
            return [
                f"{circuit_var}.measure({_operand_source(op.source)}, {op.target.name})"
            ]

        if isinstance(op, PhaseOp):
            return [f"{circuit_var}.global_phase += {self.expression(op.angle)}"]

        if isinstance(op, QIfOp):
            return self._qif_lines(op, circuit_var)

        if isinstance(op, ArithmeticOp):
            return self._arithmetic_lines(op, circuit_var)

        if isinstance(op, MultiplyOp):
            return self._multiply_lines(op, circuit_var)

        raise NotImplementedError(f"no code generation for {type(op).__name__}")

    def _declare_ancilla(self, ref: QubitRef, circuit_var: str) -> list[str]:
        return [
            f'{ref.name} = QuantumRegister({ref.size}, "{ref.name}")',
            f"{circuit_var}.add_register({ref.name})",
        ]

    def _arithmetic_lines(self, op: ArithmeticOp, circuit_var: str) -> list[str]:
        lines = self._declare_ancilla(op.helper, circuit_var)

        constant_ancilla: QubitRef | None = None
        encode_bits: list[int] = []
        if op.encode_constant is not None:
            (addend_ancilla,) = op.addend
            assert isinstance(addend_ancilla, QubitRef)
            constant_ancilla = addend_ancilla
            lines += self._declare_ancilla(constant_ancilla, circuit_var)
            encode_bits = [
                bit
                for bit in range(constant_ancilla.size)
                if (op.encode_constant >> bit) & 1
            ]
            for bit in encode_bits:
                lines.append(f"{circuit_var}.x({constant_ancilla.name}[{bit}])")
        else:
            for operand in op.addend:
                if isinstance(operand, QubitRef) and operand.origin == "ancilla":
                    lines += self._declare_ancilla(operand, circuit_var)

        self.needs_cdkm_adder = True
        adder = f"CDKMRippleCarryAdder({op.target.size}, kind='fixed')"
        gate = f"{adder}.inverse()" if op.subtract else adder
        qubits = ", ".join(
            [
                *(_spread_source(operand) for operand in op.addend),
                _spread_source(op.target),
                f"{op.helper.name}[0]",
            ]
        )
        lines.append(f"{circuit_var}.append({gate}, [{qubits}])")

        if constant_ancilla is not None:
            for bit in encode_bits:
                lines.append(f"{circuit_var}.x({constant_ancilla.name}[{bit}])")

        return lines

    def _multiply_lines(self, op: MultiplyOp, circuit_var: str) -> list[str]:
        lines: list[str] = []
        if not op.inverse:
            lines += self._declare_ancilla(op.helper, circuit_var)
            for operand in [*op.left, *op.right]:
                if isinstance(operand, QubitRef) and operand.origin == "ancilla":
                    lines += self._declare_ancilla(operand, circuit_var)
            if op.product.origin == "ancilla":
                lines += self._declare_ancilla(op.product, circuit_var)

        self.needs_hrs_multiplier = True
        width = sum(_operand_width(operand) for operand in op.left)
        multiplier = (
            f"HRSCumulativeMultiplier({width}, num_result_qubits={op.product.size})"
        )
        gate = f"{multiplier}.inverse()" if op.inverse else multiplier
        qubits = ", ".join(
            [
                *(_spread_source(operand) for operand in op.left),
                *(_spread_source(operand) for operand in op.right),
                _spread_source(op.product),
                f"{op.helper.name}[0]",
            ]
        )
        lines.append(f"{circuit_var}.append({gate}, [{qubits}])")
        return lines

    def _state_preparation_lines(self, op: InitOp, circuit_var: str) -> list[str]:
        assert isinstance(op.value, list)
        probabilities = op.value

        if not probabilities:
            return [
                f"{circuit_var}.h({op.target.name}[{bit}])"
                for bit in range(op.target.size)
            ]

        self.needs_state_preparation = True
        total = sum(probabilities)
        amplitudes = [math.sqrt(probability / total) for probability in probabilities]
        rendered = ", ".join(repr(amplitude) for amplitude in amplitudes)
        return [f"{circuit_var}.append(StatePreparation([{rendered}]), {op.target.name})"]

    def _qif_lines(self, op: QIfOp, circuit_var: str) -> list[str]:
        self._qif_counter += 1
        body_var = f"_qif_body_{self._qif_counter}"

        touched = _touched_registers(op.body)
        constructor_args = [ref.name for ref in touched] + ['name="qif_body"']
        lines = [f'{body_var} = QuantumCircuit({", ".join(constructor_args)})']
        for sub_op in op.body.ops:
            lines += self.op_lines(sub_op, body_var)
        body_sources = [f"*{ref.name}" for ref in touched]

        # Each wide-negated clause needs its own ancilla, computed before
        # everything else and uncomputed after everything else -- proper
        # last-in-first-out nesting, like any compute/uncompute pair.
        clause_computes: list[tuple[str, str]] = []
        for clause_ancilla in op.clause_ancillas:
            self.needs_xgate = True
            name = clause_ancilla.ancilla.name
            lines += self._declare_ancilla(clause_ancilla.ancilla, circuit_var)

            clause_sources = [_spread_source(q) for q in clause_ancilla.qubits]
            clause_controls = sum(_operand_width(q) for q in clause_ancilla.qubits)
            compute = (
                f"XGate().control({clause_controls}, "
                f"ctrl_state={clause_ancilla.ctrl_state}, annotated=False)"
            )
            compute_qubits = ", ".join([*clause_sources, f"{name}[0]"])
            lines.append(f"{circuit_var}.append({compute}, [{compute_qubits}])")
            lines.append(f"{circuit_var}.x({name}[0])")
            clause_computes.append((compute, compute_qubits))

        condition_sources = [_spread_source(entry) for entry in op.direct_qubits]
        total_controls = sum(_operand_width(entry) for entry in op.direct_qubits)

        if not op.negated:
            controlled = (
                f"{body_var}.to_gate().control({total_controls}, "
                f"ctrl_state={op.ctrl_state}, annotated=False)"
            )
            qubits = ", ".join([*condition_sources, *body_sources])
            lines.append(f"{circuit_var}.append({controlled}, [{qubits}])")
        else:
            # Negated, spanning more than one qubit: compute the positive
            # match into a fresh ancilla, flip it, run the body controlled by
            # just that one ancilla, flip back, and uncompute.
            self.needs_xgate = True
            assert op.ancilla is not None
            ancilla = op.ancilla.name
            lines += self._declare_ancilla(op.ancilla, circuit_var)

            compute = (
                f"XGate().control({total_controls}, ctrl_state={op.ctrl_state}, "
                "annotated=False)"
            )
            compute_qubits = ", ".join([*condition_sources, f"{ancilla}[0]"])
            lines.append(f"{circuit_var}.append({compute}, [{compute_qubits}])")
            lines.append(f"{circuit_var}.x({ancilla}[0])")

            controlled_body = f"{body_var}.to_gate().control(1, annotated=False)"
            body_qubits = ", ".join([f"{ancilla}[0]", *body_sources])
            lines.append(f"{circuit_var}.append({controlled_body}, [{body_qubits}])")

            lines.append(f"{circuit_var}.x({ancilla}[0])")
            lines.append(f"{circuit_var}.append({compute}, [{compute_qubits}])")

        # Uncompute the clause ancillas in reverse order.
        for clause_ancilla, (compute, compute_qubits) in zip(
            reversed(op.clause_ancillas), reversed(clause_computes), strict=True
        ):
            name = clause_ancilla.ancilla.name
            lines.append(f"{circuit_var}.x({name}[0])")
            lines.append(f"{circuit_var}.append({compute}, [{compute_qubits}])")

        return lines

    def expression(self, expression: Expression) -> str:
        if isinstance(expression, Literal):
            return repr(expression.value)

        if isinstance(expression, Name) and expression.name in BUILTIN_CONSTANTS:
            self.needs_numpy = True
            return PYTHON_CONSTANTS[expression.name]

        if isinstance(expression, Name) and isinstance(
            expression.resolved_symbol, ParamDecl
        ):
            return expression.name

        if isinstance(expression, Index) and isinstance(
            expression.base.resolved_symbol, ParamArrayDecl
        ):
            index = const_int(expression.index)
            return f"{expression.base.name}[{index}]"

        if isinstance(expression, UnaryOp) and expression.op in ("-", "~"):
            return f"{expression.op}{self._wrapped(expression.operand, UNARY_PRECEDENCE)}"

        if isinstance(expression, BinaryOp) and expression.op in BINARY_PRECEDENCE:
            return self._binary(expression)

        if isinstance(expression, Call) and expression.callee.name in BUILTIN_FUNCTIONS:
            return self._call(expression)

        raise SlanqError(
            f"internal error: {type(expression).__name__} cannot be rendered as Python. "
            "This is a bug in the compiler, not in the source program."
        )

    def _binary(self, expression: BinaryOp) -> str:
        precedence = BINARY_PRECEDENCE[expression.op]
        right_associative = expression.op == "**"
        left = self._wrapped(expression.left, precedence + int(right_associative))
        right = self._wrapped(expression.right, precedence + int(not right_associative))
        return f"{left} {expression.op} {right}"

    def _call(self, expression: Call) -> str:
        name = expression.callee.name
        if name == "round":
            self.needs_round = True
        else:
            self.needs_math = True
        rendered = ", ".join(self.expression(argument) for argument in expression.args)
        return f"{PYTHON_FUNCTIONS[name]}({rendered})"

    def _wrapped(self, expression: Expression, minimum: int) -> str:
        rendered = self.expression(expression)
        return f"({rendered})" if _precedence(expression) < minimum else rendered


def _precedence(expression: Expression) -> int:
    if isinstance(expression, BinaryOp):
        return BINARY_PRECEDENCE.get(expression.op, ATOM_PRECEDENCE)
    if isinstance(expression, UnaryOp):
        return UNARY_PRECEDENCE
    return ATOM_PRECEDENCE


def _operand_source(operand: QubitOperand) -> str:
    if isinstance(operand, QubitBit):
        return f"{operand.ref.name}[{_qiskit_index(operand)}]"
    assert not isinstance(operand, QubitSlice)
    return operand.name


def _spread_source(operand: QubitOperand) -> str:
    """Every qubit of `operand`, unpacked in place inside a `[...]` argument
    list -- value semantics, no mirroring, same rule as `_operand_source`'s
    whole-register case."""
    if isinstance(operand, QubitBit):
        return _operand_source(operand)
    if isinstance(operand, QubitSlice):
        return f"*{operand.ref.name}[0:{operand.size}]"
    return f"*{operand.name}"


def _operand_width(operand: QubitOperand) -> int:
    return 1 if isinstance(operand, QubitBit) else operand.size


def _qiskit_index(bit: QubitBit) -> int:
    """Slanq indexes big-endian -- index 0 is the most significant qubit --
    while the Qiskit register is little-endian."""
    return bit.ref.size - 1 - bit.index


def _touched_registers(body: IRBlock) -> list[QubitRef]:
    """The distinct outer registers a qif body's gates target, in the order
    first referenced -- becomes both the local sub-circuit's own registers
    and, unpacked, the tail of the qubit list passed to circuit.append()."""
    seen: dict[QubitRef, None] = {}
    for op in body.ops:
        if isinstance(op, GateOp):
            for target in op.targets:
                seen[target if isinstance(target, QubitRef) else target.ref] = None
    return list(seen)


__all__ = ["generate_qiskit"]
